[project]
name = "word-book"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=2.29.0",
    "pyperclip>=1.9.0",
    "python-dotenv>=1.2.2",
    "rich>=14.1.0",
    "typer>=0.24.1",
]

[project.scripts]
wordbook = "word_book.cli:app"


[build-system]
requires = ["uv_build>=0.8.14"]
build-backend = "uv_build"